### ISSUE TITLE
Custom example 

### ISSUE THREAD

**Issue by Carnaux** [kalwalt/AR.js#3]
@kalwalt I'm trying to isolate only what the NFT example needs, but I'm getting a 404 from the artoolkit worker.  The example is from V3 branch.

The error occurs after  `Pattern ratio size set to 0.500000.`

onError | @ | artoolkit.worker.js:49
(anonymous) | @ | artoolkit.min.js:1
oReq.onload | @ | artoolkit.min.js:1
load (async)  
ajax | @ | artoolkit.min.js:1
loadCamera | @ | artoolkit.min.js:1
ARCameraParam.load | @ | artoolkit.min.js:1
ARCameraParam | @ | artoolkit.min.js:1
load | @ | artoolkit.worker.js:53
self.onmessage | @ | artoolkit.worker.js:8

Project structure:

- vendor
   - jsartoolkit
      - ...
- src
   - ar.min
   - three.min
   - pinball files
   - camera.para.dat
   - gltf loader
- flamingo.gb
- nft.html

**Comment by Carnaux** [comment]
Got it to work. 

It was the `var path = '../../';` at artoolkit.worker; line 25 in the loader function.

It gets the `descriptorsUrl` from the markerControls and tries to make it relative from where the artoolkit.worker is.

`ar.loadNFTMarker(path + msg.marker .....`

**Comment by kalwalt** [comment]
@Carnaux maybe @nicolocarpignoli changes the path for the aframe example, i know that should be improved.

**Comment by kalwalt** [comment]
You should try both examples, aframe and Three.js for a comparison.

**Comment by kalwalt** [comment]
I hope to have a bit of time tomorrow to continue in the development of this!

**Comment by Carnaux** [comment]
Maybe we can implement an automatic relative path solver. It would get the full path to the marker and the full path to the worker and solve it.

**Comment by Carnaux** [comment]
> You should try both examples, aframe and Three.js for a comparison.

I will test it!

**Comment by Carnaux** [comment]
Adding another thing:

`var worker = new Worker(
      THREEx.ArToolkitContext.baseURL +
        "vendor/jsartoolkit5/js/artoolkit.worker.js"
 );` 
at `ar.min.js` in the `handleNFT` function

This path might fail(in some project architecture) using Github Pages since it ignores the "vendor" directory.

**Comment by kalwalt** [comment]
I think the worker should be injected not with a path but with a Blob object, in this way we should avoid that issue. But i didn't tested yet, because we would do this in a second moment as the ratio issue was the main issue.

**Comment by kalwalt** [comment]
I would continue this discussion but it's very late here! I'm sorry... :slightly_smiling_face:
